		CREATE TABLE `PERSONAJE`(
		ID_PERSONAJE  INTEGER PRIMARY KEY AUTOINCREMENT,
		ID_USUARIO INT NOT NULL,
		ID_RAZA INT NOT NULL,
		ID_CASTA INT NOT NULL,
		ID_MAPA INT NOT NULL
		NIVEL INT NOT NULL,
		EXPERIENCIA INT NOT NULL,
		VIDA INT NOT NULL,
		ENERGIA INT NOT NULL,
		ATAQUE INT NOT NULL,
		DEFENSA INT NOT NULL,
		MANA INT NOT NULL,
		PUNTOS INT NOT NULL,
		MAPA VARCHAR(20) NOT NULL,
		FOREIGN KEY(ID_RAZA) REFERENCES RAZA(ID_RAZA),
		FOREIGN KEY(ID_CASTA) REFERENCES CASTA(ID_CASTA),
		FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
		FOREIGN KEY(ID_MAPA) REFERENCES MAPA(ID_MAPA)
		);

		CREATE TABLE `USUARIO`(
		ID_USUARIO  INTEGER PRIMARY KEY AUTOINCREMENT,
		NOMBRE NVARCHAR(20) NOT NULL,
		CONTRASENA NVARCHAR(64) NOT NULL
		);

		CREATE TABLE `RAZA`(
		ID_RAZA  INTEGER PRIMARY KEY AUTOINCREMENT,
		RAZA VARCHAR(16) NOT NULL
		);

		CREATE TABLE `CASTA`(
		ID_CASTA  INTEGER PRIMARY KEY AUTOINCREMENT,
		CASTA VARCHAR(16) NOT NULL
		);

		CREATE TABLE 'MAPA'(
		ID_MAPA INTEGER PRIMARY KEY AUTOINCREMENT,
		MAPA VARCHAR(20) NOT NULL
		);


		INSERT INTO `RAZA` VALUES
		(1,'HUMANO'),
		(2,'ORCO'),
		(3,'ELFO');

		INSERT INTO `CASTA` VALUES
		(1,'GUERRERO'),
		(2,'MAGO'),
		(3,'PALADIN');

		INSERT INTO `USUARIO` VALUES
		(1,'Nico','');

		INSERT INTO `PERSONAJE` VALUES
		(1,1,1,1,0,0,0,0,0,0,0,0,0,0,0);

